[package]
name = "secure-web-applictions-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
derive-getters = "0.4.0"
derive-new = "0.6.0"
derive_builder = "0.20.0"
rand = "0.8.5"
strum = "0.26.2"
strum_macros = "0.26.4"
thiserror = "1.0.61"
